### PR TITLE
Form updates, requesting preliminary testing and feedback, please. Do not merge.

### PR DESCRIPTION
**Pull request by br2490**
# About this PR

...begins the framework for the form and crosswalk.  Primarily looking for feedback from folks if I'm getting the concept right. Usually working on the back-end and don't know if I'm accomplishing goals. 
## What _Might_ Work

When you click on CSV import from a collection it will poll the cmodels, namespaces, and xml forms associated with that collection. It will display them and allow the user to pick each, set as active/inactive, specify delimiter and upload a file. ~~Note that there is currently no AJAX so changing the cmodel will not change options in lists. I'm assuming _this_ is something that is required and needed.~~
## Feedback Requested

When opening the form does it display:
The correct CModels?
The correct associated XML forms?
The correct namespaces in the collection?
Is this functioning how the module should? Are we (am I) on the right path?
Etc.

tagging: @petermacdonald @jjdipasquale @patdunlavey 
and @Islandora-Collaboration-Group/icg-members 

**PLEASE DO NOT MERGE THIS PR!**

### CODE REVIEW

**Comment by br2490** [comment]
AJAX - maybe someone more adept at XHR can take a look and write a proper function!

**Comment by patdunlavey** [comment]
Hi Ben,

I like what you're doing and I think with #ajax you are taking this in a good direction but I'm afraid it's going to be a few days before I can really look at what you've done.

Best, Pat

**Comment by br2490** [comment]
Thanks Pat,

I appreciate that. 

I'm also wondering if a single cCollection can have multiples of the same type cmodel collections (e.g. PDF) each w/ unique namespaces. I don't see why not, right? If this is the case I do _not_ think my code as it stands with grab each unique namespace.

Best

**Comment by br2490** [comment]
@SummittDweller tagging you after reading Joanna's doc re on-going coordination of code for this module.

**Comment by McFateM** [comment]
Hello gentlemen and thanks for tagging me in.  I apologize, the least couple of days have been exceptionally busy... I'm pitching a new project plan (purely Drupal, no Islandora parts) for some work that has come my way, and we are preparing to interview candidates for a new College Librarian (Director) next week.  

I have not looked at this PR in any detail yet and just wanted to know if you need me in that capacity for this portion of the project?  Frankly, **I would prefer not to review this if Pat is willing to do so, and I am in no hurry.**  Pat: You are infinitely more qualified to do this than I am, and I'm keeping busy with the batch.inc parts of the code now.  

I did make some progress on batch.inc last weekend and hope to complete some unit testing today so that I can possibly create a PR of my own tomorrow.  If my code works as expected, this project should have a "headless" but working back-end to run with.  So, if someone is inclined to build a relatively simple CSV structure, complete with XPaths mapped to the data, then they should be able to install the module and put it to use (or at least through its paces in some use case testing).

Sorry to hi-jack this thread but I also wanted to let you know that the XSLT solution I was looking at for generating XML from XPaths worked wonderfully!  But it required XSLT 2.0 and it appears that our Islandora servers may never have that.  8^(  So I backed off and wrote something completely different with NO dependencies...but so far it is working nicely for most, if not all, of the cases I think we intend to cover.

**Comment by McFateM** [comment]
Oops, I just noticed the **PLEASE DO NOT MERGE** portion of the comments, so maybe I haven't hijacked this thread at all. 8^)  Seriously, I'm used to working in the back-end too so commenting on this is probably best left to others.  If my tests go well I'll post what I have and then try to give this some attention too, if only to better understand more of the code.  Thanks.

**Comment by br2490** [comment]
@McFateM tis' okay :+1:. When you commit & push your backend stuff could you ping me? I'll integrate it with the GUI and Pat can have at it. In so far as I'm concerned _this_ commit is fine and could be merged with the exception of the unanswered questions: 

> I'm also wondering if a single cCollection can have multiples of the same type cmodel collections (e.g. PDF) each w/ unique namespaces. I don't see why not, right? If this is the case I do not think my code as it stands with grab each unique namespace.

Folks can go on their own Vagrant and 'git fetch && git checkout development' to see the current GUI.

**Comment by patdunlavey** [comment]
Closing at request of Ben Rosner - who issued the initial pull request

**Pull request closed without merging**
